[tool.semantic_release]
version = "0.0.0"
version_variable = [
    "pyproject.toml:version"
]
version_pattern = [
    "README.md:^      version: v{version}"
]
upload_to_pypi = false
upload_to_release = false
commit_subject = "chore(release): {version}  [skip actions]"
