[tool.semantic_release]
version = "0.1.0"
version_variable = [
    "pyproject.toml:version"
]
version_pattern = [
    "{{cookiecutter.project_slug}}/README.md:.+blueprint-ansible-role/tree/v{version}"
]
upload_to_pypi = false
upload_to_release = false
commit_subject = "chore(release): {version} [skip actions]"
